### ISSUE TITLE
[impossible XSS] Attribute length 20 chars - arbitrary code

### ISSUE THREAD

**Issue by dostoevskylabs** [PortSwigger/xss-cheatsheet-data#11]
I found a solution with the new limit of 20 characters but never got a response on twitter. I was worried it got lost in the aether :( so I'm posting it here.

It works by using document.cookie to store the payload, and appears to work whether cookies are already present on the site or not!

http://jsfiddle.net/dostoevskylabs/4bhjLnw2/2/

stage 1 and 2 are triggered by clicking the input in the order opened, stage 3 by cutting the input on the last page.

**Comment by hackvertor** [comment]
Hi dostoevskylabs 
The new windows will be blocked by the popup blocker. Please supply a vector that doesn't get blocked by the popup blocker. Thanks.

**Comment by stayanonymous** [comment]
Window open isn’t necessary I just included it to open the windows for you

**Comment by dostoevskylabs** [comment]
Window.open isn't part of the vector, i just put that in there to open the three pages for you. You can just open each link manually by copying the URLs

**Comment by hackvertor** [comment]
This isn't practical for an attack. You should have used iframes like some of the other solvers. The new limit is now 17.

**Comment by dostoevskylabs** [comment]
How are iframes that require you to click multiple iframes more practical? They require you to go to a third party site and require the user to perform multiple actions to trigger it.

For example if this input field was in the real world and had an autofocus attribute, you would only need the victim to visit the first two links and perform no action.

The third would be no different than the original of using a cut on the input.

Oh well, I thought it was a clever idea without using a third party site to trigger it.

Thanks anyway

**Comment by hackvertor** [comment]
I think your fiddle didn't help. Using window.open to conduct the attack didn't make much sense. It's a nice attack but roman already used this style of attack earlier.

**Comment by dostoevskylabs** [comment]
Fair enough, I was just trying to make your life easier with the fiddle but i explained it in comments.

All good, thanks for your time!
