### ISSUE TITLE
Copy & Paste XSS-es

### ISSUE THREAD

**Issue by securityMB** [PortSwigger/xss-cheatsheet-data#12]
To raise awareness of the copy&paste XSS-es, I think it'd be great if they were included in your cheat sheet. I am not, though, sure how to do it.

I guess we should create a new JSON file (like copy-paste.json) and include the payloads in there? It would also be awesome if "Copy vector to clipboard" in the cheat sheet copied it as text/html to make it easier to use them for testing.

**Comment by hackvertor** [comment]
Yep agreed it would be great!

If you create the JSON file and the vectors. I'll add them to the cheat sheet. I'll sort it so it uses the right code when copying to clipboard. Thanks.
