### ISSUE TITLE
Extension template

### ISSUE THREAD

**Issue by michaelkruglos** [PortSwigger/xss-cheatsheet-data#18]
Not sure where to ask it, but could you please, create a template for writing plugins/extensions for Burp?

**Comment by hackvertor** [comment]
This is not the correct place to submit questions about BApps. This is for contributing to the XSS cheat sheet. 

If you need help with writing a BApp you might want to start here:
https://portswigger.net/burp/extender/writing-your-first-burp-suite-extension

Please contact support if you have any questions or suggestions:
https://portswigger.net/support
