### ISSUE TITLE
copy payloads to clipboard

### ISSUE THREAD

**Issue by ghanisol** [PortSwigger/xss-cheatsheet-data#21]
Wouldn't it be better if we could just copy only the payloads that we filtered out e.g if we select "custom tags", "all events", "firefox" in the filter, "copy payloads to clipboard" only copies all the custom tags for all the events if custom tag is available for the respective event. I'm not sure if that functionality already exists. Do let me know if it does.

**Comment by hackvertor** [comment]
Yep that's a good suggestion. I'll update the JS to do that in the next release.

**Comment by hackvertor** [comment]
This has been done and will be in the next release
