### ISSUE TITLE
Display browser compatibility for all sections

### ISSUE THREAD

**Issue by jkmartindale** [PortSwigger/xss-cheatsheet-data#25]
The **Event handlers** section has a handy column listing browser support for each event handler, but this display is missing from many other sections that declare limited browser compatibility in the JSON. I found this out after trying to debug a payload that "stopped working" without realizing that it only works in Firefox.

It would be nice to either add the browser compatibility icons to other sections or change entry titles to indicate browser-specific behavior.

**Comment by hackvertor** [comment]
We released it without showing that information for certain sections so we should definitely update the HTML to display that information. We'll update it in the next release thanks.

**Comment by hackvertor** [comment]
I've implemented this for all sections now, the website will be updated soon. Cheers and thanks for the report!
