### ISSUE TITLE
discard tag missing from list of tags

### ISSUE THREAD

**Issue by Sanduuz** [PortSwigger/xss-cheatsheet-data#26]
The list containing tags is missing the `<discard>` tag. 
![image](https://user-images.githubusercontent.com/26064233/139445473-e2d5043a-ea81-48a7-b078-b48502678357.png)
However, there is an example that uses it.
![image](https://user-images.githubusercontent.com/26064233/139445524-52912ce8-1103-4521-87a0-da8af9e50471.png)

Please add the option for the discard tag in the tag list.

**Comment by hackvertor** [comment]
I don't think any modern browser supports this anymore. Not much point in adding it back.
