### ISSUE TITLE
filtered list

### ISSUE THREAD

**Issue by n1njaZ0Z** [PortSwigger/xss-cheatsheet-data#35]
is it possible (and make sense) to be able to filter the list to eliminate blacklisted (or show only whitelisted) tags / events / attributes / etc.

so if the WAF filters <svg> tags and  "href" attributes (for example) I will be able to see only payloads that do not contain any of them

**Comment by hackvertor** [comment]
Hi you can already multi select tags etc by using control

**Comment by n1njaZ0Z** [comment]
...and its a great feature. 
but what if i know that the WAF filters <svg> tags and I want to see all the payload *besides* payload that contains the <svg> tag?
this can be very useful feature as well

**Comment by n1njaZ0Z** [comment]
yep i guess this qualifies as a solution. thanks
(though it would be nice to also be able to avoid expressions - like href when you know waf blocks it)

**Comment by hackvertor** [comment]
I'll add a regex search which will make this easier

**Comment by n1njaZ0Z** [comment]
cool thnx  
awesome tool you got there going. respect

**Comment by hackvertor** [comment]
This has been implemented and will be in the next release. You can do a regex by tag or event.
