### ISSUE TITLE
Re-add older credits?

### ISSUE THREAD

**Issue by mornau** [PortSwigger/xss-cheatsheet-data#44]
Thanks for continuing to maintain the XSS cheat sheet originally developed and maintained by Robert Hansens on [https://ha.ckers.org/xss.html](https://web.archive.org/web/20120911044754/https://ha.ckers.org/xss.html), before it moved to what is now https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html
Back in the days (as seen in both of the above linked copies), Robert had added several more credits on the page, which appear to have been lost in later edits.

I definitely do not wish to insist on it, but if it's a matter of minutes to you, I would appreciate you re-adding those, which are effectively just:
```
$ curl -s https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html | grep -Eoi 'Submitted by:? [a-z]* [a-z]*' | cut -d ' ' -f3,4 | sort | uniq
David Cross
Franz Sedlmaier
Łukasz Pilorz
Moritz Naumann
```

Thanks.

**Comment by hackvertor** [comment]
I've been through the ha.ckers cheat sheet and added the relevant contributors. This will be on the next release.
