### ISSUE TITLE
Add \x0a-\x0f

### ISSUE THREAD

**Issue by Rando111111** [PortSwigger/xss-cheatsheet-data#47]
Add \x0a-\x0f: \x0a, \x0b, \x0c, \x0d, \x0e, and \x0f.

Characters \x01-\x20 are allowed before the protocol --> Characters \x01-\x20,\x0a-\x0f are allowed before the protocol

[https://portswigger.net/web-security/cross-site-scripting/cheat-sheet#characters-x01x20-are-allowed-before-the-protocol](https://portswigger.net/web-security/cross-site-scripting/cheat-sheet#characters-x01x20-are-allowed-before-the-protocol)

**Comment by hackvertor** [comment]
\x01-\x20  means in the range of 0x01 to 0x20 so 0x0a etc will be included

**Comment by Rando111111** [comment]
Yes
