### ISSUE TITLE
[QUESTION]  classic.json payloads are too old to reproduce?

### ISSUE THREAD

**Issue by leveryd** [PortSwigger/xss-cheatsheet-data#48]
Such as [JScript.Encode payload](https://github.com/PortSwigger/xss-cheatsheet-data/blob/f9c45f99948bc4c57ee315103c655d2885c04398/json/classic.json#L28), i tried to reproduce on chrome/firefox/edge browser, can not reproduce.

I think those payloads are too old, what is your opnion?

**Comment by hackvertor** [comment]
Those payloads are in the classic section which means they are old vectors that no longer work. JScript.Encode was specific to older versions of Internet Explorer.
