### ISSUE TITLE
Add ondragexit - requires user interaction

### ISSUE THREAD

**Issue by hansmach1ne** [PortSwigger/xss-cheatsheet-data#55]
Works in firefox.

`https://portswigger-labs.net/xss/xss.php?x=%3Cdiv%20draggable=true%20ondragexit=alert(1)%3EDrag%20me%3C/div%3E&context=html`

**Comment by hackvertor** [comment]
Another good one! I'll add it to the cheat sheet

**Comment by hackvertor** [comment]
Thanks for the submission! This will be included on the cheat sheet shortly.
