### ISSUE TITLE
onwaiting can be fired with user interaction. 

### ISSUE THREAD

**Issue by hackvertor** [PortSwigger/xss-cheatsheet-data#57]
We should add onwaiting back to the cheat sheet as it can be fired when a user clicks play.

https://portswigger-labs.net/xss/xss.php?x=%3Cvideo%20width=%222222%22%20height=%222222%22%20controls%20autoplay%20muted%20onwaiting=%22alert(1)%22%3E%20%3Csource%20src=%22validvideo.mp4%22%20type=%22video/mp4%22%3E%3C/video%3E&context=html

**Comment by hackvertor** [comment]
Credits @hansmach1ne

**Comment by hackvertor** [comment]
This no longer works :(

**Comment by Osb0rn3** [comment]
Hey @hackvertor,

I found a way to get the onwaiting event handler to work. I added the loop attribute, and now it fires up when the video ends. I'll open a PR for this :)
