### ISSUE TITLE
Add onpointercancel - requires user interaction

### ISSUE THREAD

**Issue by wcraft-log** [PortSwigger/xss-cheatsheet-data#58]
# XSS via `onpointercancel`

**References:**
- https://developer.mozilla.org/en-US/docs/Web/API/Element/pointercancel_event

### Steps to Reproduce:
1. Access https://portswigger-labs.net/xss/xss.php?x=%3Cxss%20onpointercancel%3Dalert%281%29%3EXSS%3C%2Fxss%3E&context=html
1. Select the text that says **XSS**.
2. After selecting, click on the selection and hold.
3. Move the mouse to trigger the JavaScript code.

Note: The tests were performed using the latest version of Google Chrome.

**Video demonstrating the execution:** 
[<img src="https://img.youtube.com/vi/TpZiMf8QHCo/maxresdefault.jpg" width="50%">](https://youtu.be/TpZiMf8QHCo)

**Comment by hackvertor** [comment]
This will be in the next release
