### ISSUE TITLE
Attribute 'start' in the <ol> tag to trigger an alert.

### ISSUE THREAD

**Issue by TaurusOmar** [PortSwigger/xss-cheatsheet-data#61]
The 'start' attribute in the <ol> tag is used to specify from which number the ordered list should start.

Payload: [https://portswigger-labs.net/xss/xss.php?context=html&x=%3Col%20start=x%20onclick=%22alert(1)%22%3Etest%3C/ol%3E](https://portswigger-labs.net/xss/xss.php?context=html&x=%3Col%20start=x%20onclick=%22alert(1)%22%3Etest%3C/ol%3E)

Tested on: Safari,Chrome, Firefox

Credits: Taurus Omar
Twitter: @TaurusOmar_

**Comment by hackvertor** [comment]
This isn't a new XSS vector
