### ISSUE TITLE
New XSS webkit Event.

### ISSUE THREAD

**Issue by SMHTahsin33** [PortSwigger/xss-cheatsheet-data#65]
Hello,

The `onwebkitpresentationmodechanged` event triggers when a video is shifted from inline mode to fullscreen mode or vice versa.

Tested on `MacOs Sonoma (14.5); Safari Version 17.5 (19618.2.12.11.6)`

Works only on `Safari browser`. Might work on iPhone without any user interactions, as I knew It used to shift videos in fullscreen mode automatically.

Also `controls` & `autoplay` must be there. Controls allow to shift presentation mode & autoplay lessens the user interaction.

```
<video src="valid.mp4" controls autoplay onwebkitpresentationmodechanged="confirm(1337)">
```

Warm Regards

**Comment by Osb0rn3** [comment]
Hi,

Great find by @SMHTahsin33, I discovered that the `onwebkitfullscreenchange` event handler also works in Safari for making videos full screen.

You can see a quick demonstration [here](https://portswigger-labs.net/xss/xss.php?context=html&x=%3Cvideo%20controls%20onwebkitfullscreenchange=%22alert(1)%22%20src=%22validvideo.mp4%22%3E%3C/video%3E).

I'll be adding both event handlers in the next PR to make the process smoother.

**Comment by hackvertor** [comment]
Thanks both, I'll add these to the cheat sheet. Please can you post your Twitter accounts so that I can credit you.

**Comment by hackvertor** [comment]
Oh it's okay I've found them
